/**
 * Tests for Gemini CLI target bundle function.
 *
 * The parity test verifies that `bundleGeminiPlugin` produces output identical
 * to the committed `dist/gemini/skill-evaluator/` in the template repository —
 * which is the oracle generated by the original `buildGeminiStandalone`.
 *
 * Runs with positive coverage in CI against the template revision pinned in
 * `.github/template-repo.rev` (see issue #86); skips locally when no complete template checkout
 * is configured via `AIPM_TEMPLATE_REPO`.
 *
 * The `@see` links below resolve at `ai-plugin-marketplace/template`'s `main` tip for
 * readability, but the actual oracle this suite compares against is whatever revision is pinned
 * in `.github/template-repo.rev` — if this suite fails, diff against that pinned SHA
 * (`https://github.com/ai-plugin-marketplace/template/tree/<pinned-sha>/...`), not `main`, since
 * the two can diverge between pin bumps.
 *
 * @see ../../../../../.github/template-repo.rev (the pinned revision the oracle below is read from)
 * @see https://github.com/ai-plugin-marketplace/template/blob/main/src/build-standalone.ts
 *      (reference implementation)
 * @see https://github.com/ai-plugin-marketplace/template/tree/main/dist/gemini/skill-evaluator
 *      (committed oracle output)
 * @see docs/specs/architecture.md §7, §12.4
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

import { afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest';

import {
  AIPM_REQUIRE_TEMPLATE,
  assertTemplateRepoAvailable,
  shouldSkipTemplateRepoSuite,
  TEMPLATE_REPO,
  TEMPLATE_REPO_AVAILABLE,
} from '../../test-support/template-repo.js';
import { bundleGeminiPlugin } from './bundle.js';

const SKIP_PARITY_SUITE = shouldSkipTemplateRepoSuite({
  available: TEMPLATE_REPO_AVAILABLE,
  required: AIPM_REQUIRE_TEMPLATE,
});

function requireTemplateRepo(): void {
  assertTemplateRepoAvailable({
    available: TEMPLATE_REPO_AVAILABLE,
    required: AIPM_REQUIRE_TEMPLATE,
    templateRoot: TEMPLATE_REPO,
  });
}

// ---------------------------------------------------------------------------
// Paths to template repo (test-only references; never imported as code)
// ---------------------------------------------------------------------------

const PLUGIN_SRC = path.join(TEMPLATE_REPO, 'plugins', 'skill-evaluator');
const ORACLE_DIR = path.join(TEMPLATE_REPO, 'dist', 'gemini', 'skill-evaluator');

// ---------------------------------------------------------------------------
// Temp directory management
// ---------------------------------------------------------------------------

let tmpDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'gemini-bundle-test-'));
});

afterEach(() => {
  if (tmpDir && fs.existsSync(tmpDir)) {
    fs.rmSync(tmpDir, { recursive: true });
  }
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Collect all file paths under `dir` relative to `dir`, sorted. */
function collectRelativePaths(dir: string): string[] {
  const results: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      for (const sub of collectRelativePaths(path.join(dir, entry.name))) {
        results.push(path.join(entry.name, sub));
      }
    } else {
      results.push(entry.name);
    }
  }
  return results.sort();
}

// ---------------------------------------------------------------------------
// Parity test: bundleGeminiPlugin must reproduce the committed oracle
// ---------------------------------------------------------------------------

describe.skipIf(SKIP_PARITY_SUITE)(
  'bundleGeminiPlugin — parity with dist/gemini/skill-evaluator',
  () => {
    beforeAll(requireTemplateRepo);

    it('produces the exact same set of file paths as the oracle', () => {
      const destDir = path.join(tmpDir, 'out');
      bundleGeminiPlugin(PLUGIN_SRC, destDir);

      const actual = collectRelativePaths(destDir);
      const expected = collectRelativePaths(ORACLE_DIR);

      expect(actual).toStrictEqual(expected);
    });

    it('produces byte-identical content for every file compared to the oracle', () => {
      const destDir = path.join(tmpDir, 'out');
      bundleGeminiPlugin(PLUGIN_SRC, destDir);

      const filePaths = collectRelativePaths(destDir);
      for (const rel of filePaths) {
        const actualContent = fs.readFileSync(path.join(destDir, rel), 'utf-8');
        const expectedContent = fs.readFileSync(path.join(ORACLE_DIR, rel), 'utf-8');
        expect(actualContent, `content mismatch for ${rel}`).toBe(expectedContent);
      }
    });

    it('returns an emitted list that matches all file paths under destDir', () => {
      const destDir = path.join(tmpDir, 'out');
      const { emitted } = bundleGeminiPlugin(PLUGIN_SRC, destDir);

      const actual = [...emitted].sort();
      const expected = collectRelativePaths(destDir);

      expect(actual).toStrictEqual(expected);
    });

    it('returns droppedToolsByAgent as empty (all skill-evaluator Claude tools map)', () => {
      const destDir = path.join(tmpDir, 'out');
      const { droppedToolsByAgent } = bundleGeminiPlugin(PLUGIN_SRC, destDir);

      expect(droppedToolsByAgent).toStrictEqual({});
    });
  },
);

// ---------------------------------------------------------------------------
// destDir clearing behaviour
// ---------------------------------------------------------------------------

describe.skipIf(SKIP_PARITY_SUITE)('bundleGeminiPlugin — destDir handling', () => {
  beforeAll(requireTemplateRepo);

  it('clears existing content in destDir before writing', () => {
    const destDir = path.join(tmpDir, 'out');

    // Pre-populate destDir with a stale file that should not survive
    fs.mkdirSync(destDir, { recursive: true });
    const staleFile = path.join(destDir, 'stale-file.txt');
    fs.writeFileSync(staleFile, 'old content');

    bundleGeminiPlugin(PLUGIN_SRC, destDir);

    // The stale file must be gone
    expect(fs.existsSync(staleFile)).toBe(false);
  });

  it('creates destDir when it does not exist yet', () => {
    const destDir = path.join(tmpDir, 'nonexistent', 'out');
    expect(fs.existsSync(destDir)).toBe(false);

    bundleGeminiPlugin(PLUGIN_SRC, destDir);

    expect(fs.existsSync(destDir)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// emitted list
// ---------------------------------------------------------------------------

describe.skipIf(SKIP_PARITY_SUITE)('bundleGeminiPlugin — emitted paths', () => {
  beforeAll(requireTemplateRepo);

  it('includes the expected canonical file paths for skill-evaluator', () => {
    const destDir = path.join(tmpDir, 'out');
    const { emitted } = bundleGeminiPlugin(PLUGIN_SRC, destDir);

    const emittedSet = new Set(emitted);

    expect(emittedSet.has('gemini-extension.json')).toBe(true);
    expect(emittedSet.has('GEMINI.md')).toBe(true);
    expect(emittedSet.has(path.join('agents', 'experimenter.md'))).toBe(true);
    expect(emittedSet.has(path.join('agents', 'test-subject.md'))).toBe(true);
    expect(emittedSet.has(path.join('skills', 'evaluate-skill', 'SKILL.md'))).toBe(true);
    expect(emittedSet.has(path.join('commands', 'evaluate.toml'))).toBe(true);
  });

  it('does not include non-.toml files from commands/', () => {
    const destDir = path.join(tmpDir, 'out');
    const { emitted } = bundleGeminiPlugin(PLUGIN_SRC, destDir);

    // evaluate.md is in the source commands/ but must not be emitted
    expect(emitted.some((p) => p.endsWith('evaluate.md') && p.startsWith('commands'))).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// README.md / LICENSE exclusion (template-independent — must never be gated on
// SKIP_PARITY_SUITE: it builds its own scratch plugin dir and would otherwise
// vanish exactly when the parity oracle is unavailable to catch the regression)
// ---------------------------------------------------------------------------

describe('bundleGeminiPlugin — README.md/LICENSE exclusion', () => {
  it('does not include README.md/LICENSE even when present in pluginDir (root-owned shared artifacts)', () => {
    // Regression for issue #89: the template repo (commit d2d9923) moved README.md/LICENSE from
    // per-plugin source to the repo root, where they are canonical shared artifacts (GeneratedFile
    // .target's 'shared' model, #54) — the bundler must never treat them as per-plugin bundle
    // content, even when a stray copy exists in pluginDir.
    const destDir = path.join(tmpDir, 'out');
    const scratchPlugin = path.join(tmpDir, 'plugin-with-readme');
    fs.mkdirSync(scratchPlugin, { recursive: true });
    fs.writeFileSync(path.join(scratchPlugin, 'gemini-extension.json'), '{}\n');
    fs.writeFileSync(path.join(scratchPlugin, 'README.md'), '# stray\n');
    fs.writeFileSync(path.join(scratchPlugin, 'LICENSE'), 'MIT\n');

    const { emitted } = bundleGeminiPlugin(scratchPlugin, destDir);

    expect(emitted).not.toContain('README.md');
    expect(emitted).not.toContain('LICENSE');
    expect(fs.existsSync(path.join(destDir, 'README.md'))).toBe(false);
    expect(fs.existsSync(path.join(destDir, 'LICENSE'))).toBe(false);
  });
});
