/**
 * Generated-file sentinels.
 *
 * Per §4.3 of the architecture spec, every toolkit-generated file carries a sentinel so
 * hand-edits are detectable by the freshness check (§10.5). There are three carriers:
 *
 * 1. **Inline text** — a comment block prepended to plain-text generated files.
 * 2. **JSON `_generated` field** — a top-level object on JSON outputs that tolerate extra keys.
 * 3. **Sidecar `<artifact>.generated`** — a companion file holding the inline-text body, used
 *    for strict-schema hosts that reject unknown top-level fields (Gemini's
 *    `gemini-extension.json`, Kiro's `.kiro/agents/*.json`).
 *
 * This module is **pure**: string/object in, string out. It performs no filesystem I/O — the
 * build (§5.2) and freshness (§10.5) layers own all reads and writes. It is internal to
 * `@ai-plugin-marketplace/core` and intentionally NOT re-exported from the package root.
 *
 * Round-trip invariants hold for every carrier:
 * - `stripSentinel(applyXSentinel(x, src), mode) === x`
 * - `readSentinelSource(applyXSentinel(x, src), mode) === src`
 *
 * @see docs/specs/architecture.md §4.3 (author-authored vs toolkit-generated — governing section)
 * @see docs/specs/architecture.md §10.5 (freshness check — consumer of the detect/strip helpers)
 * @see docs/specs/architecture.md §5.2 (build phase — consumer of the apply helpers)
 */

import type { ClaudeHooksFile } from '../targets/claude/schemas.js';

/**
 * Canonical generator identity string embedded in every sentinel. Centralized here so the
 * inline comment block, the JSON `_generated.by` field, and any detector all agree on one
 * literal — there is no second copy to drift.
 */
export const GENERATOR_ID = '@ai-plugin-marketplace/cli';

/**
 * Which sentinel carrier a given generated file uses. Selected by the build step per the
 * artifact's format and host tolerance (§4.3):
 * - `'inline'` — plain-text outputs (comment block prepended).
 * - `'json-field'` — JSON outputs that tolerate an extra top-level `_generated` key.
 * - `'sidecar'` — strict-schema JSON whose host rejects unknown fields; sentinel lives in
 *   a companion `<artifact>.generated` file and the artifact itself is left untouched.
 */
export type SentinelMode = 'inline' | 'json-field' | 'sidecar';

/**
 * Shape of the top-level `_generated` field used by the JSON carrier (§4.3). Serialized with
 * the `_generated` key FIRST so the sentinel is visible at the head of the file.
 */
export interface JsonSentinelField {
  /** The {@link GENERATOR_ID} that produced the file. */
  by: string;
  /** Author-authored source path this file was generated from, relative to the plugin dir. */
  source: string;
}

// ---------------------------------------------------------------------------
// Inline-text carrier
// ---------------------------------------------------------------------------

/** First line of the inline/sidecar comment body. */
const INLINE_LINE_1 = `# Generated by ${GENERATOR_ID}. Do not edit directly.`;
/** Second line of the inline/sidecar comment body. */
const INLINE_LINE_2 = '# Edit the source file listed in the sentinel and run `aipm build`.';
/** Prefix of the third (source) line; the relative source path is appended verbatim. */
const INLINE_SOURCE_PREFIX = '# source: ';

/**
 * Build the canonical inline-text sentinel body for a source path. This three-line block is
 * shared by the inline carrier (prepended to content) and the sidecar carrier (used as the
 * whole sidecar file). Always terminated by a trailing newline so the following content — or
 * the file end, for a sidecar — starts on a fresh line.
 *
 * @param source - Author-authored source path, relative to the plugin directory.
 * @returns The three-line comment block, newline-terminated.
 */
function inlineSentinelBlock(source: string): string {
  return `${INLINE_LINE_1}\n${INLINE_LINE_2}\n${INLINE_SOURCE_PREFIX}${source}\n`;
}

/**
 * Prepend the inline-text sentinel (§4.3) to a plain-text generated file's content.
 *
 * @param content - The generated file body, sans sentinel.
 * @param source - Author-authored source path, relative to the plugin directory.
 * @returns Content with the three-line sentinel block prepended.
 */
export function applyInlineSentinel(content: string, source: string): string {
  return inlineSentinelBlock(source) + content;
}

// ---------------------------------------------------------------------------
// Sidecar carrier
// ---------------------------------------------------------------------------

/** Suffix appended to an artifact path to form its sidecar sentinel path. */
const SIDECAR_SUFFIX = '.generated';

/**
 * The body of a `<artifact>.generated` sidecar file (§4.3). Identical to the inline-text
 * sentinel block — the sidecar carries no artifact content, only the sentinel.
 *
 * @param source - Author-authored source path, relative to the plugin directory.
 * @returns The three-line sentinel block, newline-terminated.
 */
export function sidecarContent(source: string): string {
  return inlineSentinelBlock(source);
}

/**
 * Derive the sidecar sentinel path for an artifact: `<artifactPath>.generated` (§4.3). The
 * sidecar sits next to the artifact; the artifact itself is left untouched.
 *
 * @param artifactPath - Path to the strict-schema artifact (e.g. `gemini-extension.json`).
 * @returns The sidecar path.
 */
export function sidecarPath(artifactPath: string): string {
  return `${artifactPath}${SIDECAR_SUFFIX}`;
}

// ---------------------------------------------------------------------------
// JSON `_generated`-field carrier
// ---------------------------------------------------------------------------

/**
 * Serialize an object as canonical JSON with a top-level `_generated` sentinel (§4.3). The
 * `_generated` key is emitted FIRST, every other own-enumerable key follows in its original
 * order, and the output uses 2-space indentation with a trailing newline — matching the JSON
 * conventions in `claude/transform.ts`'s `serializeClaudeHooksJson`.
 *
 * Any pre-existing `_generated` key on the input is overwritten by the fresh sentinel rather
 * than duplicated, so re-applying is idempotent at the field level.
 *
 * @param obj - The value to serialize. Treated as a string-keyed object; non-object inputs
 *   (arrays, primitives) cannot carry a top-level field and are rejected.
 * @param source - Author-authored source path, relative to the plugin directory.
 * @returns Canonical JSON string with `_generated` first and a trailing `\n`.
 * @throws {TypeError} If `obj` is not a plain JSON object (null, array, or primitive).
 */
export function applyJsonSentinel(obj: unknown, source: string): string {
  if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) {
    throw new TypeError(
      'applyJsonSentinel: expected a plain object to carry a top-level _generated field',
    );
  }

  const sentinel: JsonSentinelField = { by: GENERATOR_ID, source };

  // `_generated` first, then every other own key in its original insertion order. Spreading a
  // pre-existing `_generated` would re-introduce it after ours, so drop it from the rest.
  const rest: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key === '_generated') continue;
    rest[key] = value;
  }

  const withSentinel = { _generated: sentinel, ...rest };
  return JSON.stringify(withSentinel, null, 2) + '\n';
}

/**
 * Convenience overload for validated Claude hooks data, matching the call shape of
 * `serializeClaudeHooksJson`. Equivalent to {@link applyJsonSentinel} with the hooks object.
 *
 * @param data - Validated {@link ClaudeHooksFile}.
 * @param source - Author-authored source path, relative to the plugin directory.
 * @returns Canonical JSON string with `_generated` first and a trailing `\n`.
 */
export function applyJsonSentinelToHooks(data: ClaudeHooksFile, source: string): string {
  return applyJsonSentinel(data, source);
}

// ---------------------------------------------------------------------------
// Detection / source extraction / stripping (consumed by freshness — §10.5)
// ---------------------------------------------------------------------------

/**
 * Parse JSON content into a string-keyed object, returning `undefined` for malformed JSON or
 * any non-object top-level value (array, primitive, null). Used by the JSON-carrier detectors
 * so a hand-corrupted generated file degrades gracefully rather than throwing.
 */
function parseJsonObject(content: string): Record<string, unknown> | undefined {
  let parsed: unknown;
  try {
    parsed = JSON.parse(content);
  } catch {
    return undefined;
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    return undefined;
  }
  return parsed as Record<string, unknown>;
}

/**
 * Read the `source` from a JSON `_generated` field, validating that the field is a well-formed
 * {@link JsonSentinelField}. Returns `undefined` if absent or malformed.
 */
function readJsonSentinelSource(content: string): string | undefined {
  const obj = parseJsonObject(content);
  if (!obj) return undefined;
  const generated = obj._generated;
  if (typeof generated !== 'object' || generated === null || Array.isArray(generated)) {
    return undefined;
  }
  const source = (generated as Record<string, unknown>).source;
  return typeof source === 'string' ? source : undefined;
}

/**
 * Read the `source` from an inline/sidecar comment block. Returns `undefined` if the content
 * does not begin with the canonical two-line preamble followed by a `# source:` line.
 */
function readInlineSentinelSource(content: string): string | undefined {
  const lines = content.split('\n');
  if (lines[0] !== INLINE_LINE_1 || lines[1] !== INLINE_LINE_2) return undefined;
  const sourceLine = lines[2];
  if (!sourceLine?.startsWith(INLINE_SOURCE_PREFIX)) return undefined;
  return sourceLine.slice(INLINE_SOURCE_PREFIX.length);
}

/**
 * Detect whether `content` carries a sentinel for the given carrier (§4.3). For `'sidecar'`,
 * `content` is the sidecar file body (same shape as inline); the artifact itself is never
 * inspected by this function.
 *
 * @param content - File content to inspect (artifact body, or sidecar body for `'sidecar'`).
 * @param mode - Which carrier to check for.
 * @returns `true` iff a well-formed sentinel of that carrier is present.
 */
export function hasSentinel(content: string, mode: SentinelMode): boolean {
  return readSentinelSource(content, mode) !== undefined;
}

/**
 * Extract the author-authored source path recorded in a sentinel, or `undefined` if no
 * well-formed sentinel of the given carrier is present (§10.5 uses this to identify the source
 * and to distinguish generated files from hand-authored ones).
 *
 * @param content - File content to inspect (artifact body, or sidecar body for `'sidecar'`).
 * @param mode - Which carrier to read.
 * @returns The recorded source path, or `undefined`.
 */
export function readSentinelSource(content: string, mode: SentinelMode): string | undefined {
  switch (mode) {
    case 'inline':
    case 'sidecar':
      return readInlineSentinelSource(content);
    case 'json-field':
      return readJsonSentinelSource(content);
  }
}

/**
 * Remove a sentinel from `content`, returning the body sans sentinel. The inverse of the
 * matching `applyXSentinel`, so freshness (§10.5) can compare an on-disk generated file to
 * freshly-built content modulo the sentinel.
 *
 * - `'inline'` — drops the three-line comment block if present; otherwise returns `content`
 *   unchanged.
 * - `'sidecar'` — the sidecar carries only the sentinel, so the stripped body is the empty
 *   string; if `content` is not a recognized sidecar it is returned unchanged.
 * - `'json-field'` — re-serializes the object without `_generated`, preserving the remaining
 *   keys' order, 2-space indent, and trailing newline. Malformed JSON is returned unchanged.
 *
 * @param content - File content to strip.
 * @param mode - Which carrier to strip.
 * @returns The content with its sentinel removed.
 */
export function stripSentinel(content: string, mode: SentinelMode): string {
  switch (mode) {
    case 'inline':
      return stripInlineSentinel(content);
    case 'sidecar':
      // A sidecar is wholly sentinel; stripping yields an empty body. Leave unrecognized
      // content untouched so a non-sidecar file is not silently emptied.
      return hasSentinel(content, 'sidecar') ? '' : content;
    case 'json-field':
      return stripJsonSentinel(content);
  }
}

/** Drop the leading three-line inline sentinel block, if present. */
function stripInlineSentinel(content: string): string {
  if (readInlineSentinelSource(content) === undefined) return content;
  // The block is exactly three newline-terminated lines; remove up to and including the third
  // newline. Locate it without assuming the source path is newline-free beyond line 3.
  const firstNl = content.indexOf('\n');
  const secondNl = content.indexOf('\n', firstNl + 1);
  const thirdNl = content.indexOf('\n', secondNl + 1);
  return content.slice(thirdNl + 1);
}

/** Re-serialize JSON content without its `_generated` field; passthrough on malformed JSON. */
function stripJsonSentinel(content: string): string {
  const obj = parseJsonObject(content);
  if (!obj) return content;
  const rest: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key === '_generated') continue;
    rest[key] = value;
  }
  return JSON.stringify(rest, null, 2) + '\n';
}
