/**
 * Generated-file sentinels.
 *
 * Per §4.3 of the architecture spec, every toolkit-generated file carries a sentinel so
 * hand-edits are detectable by the freshness check (§10.5). There are three carriers:
 *
 * 1. **Inline text** — a comment block prepended to plain-text generated files.
 * 2. **JSON `_generated` field** — a top-level object on JSON outputs that tolerate extra keys.
 * 3. **Sidecar `<artifact>.generated`** — a companion file holding the inline-text body, used
 *    for strict-schema hosts that reject unknown top-level fields (Gemini's
 *    `gemini-extension.json`, Kiro's `.kiro/agents/*.json`).
 *
 * This module is **pure**: string/object in, string out. It performs no filesystem I/O — the
 * build (§5.2) and freshness (§10.5) layers own all reads and writes. It is internal to
 * `@ai-plugin-marketplace/core` and intentionally NOT re-exported from the package root.
 *
 * Round-trip invariants hold for every carrier:
 * - `stripSentinel(applyXSentinel(x, src), mode) === x`
 * - `readSentinelSource(applyXSentinel(x, src), mode) === src`
 *
 * @see docs/specs/architecture.md §4.3 (author-authored vs toolkit-generated — governing section)
 * @see docs/specs/architecture.md §10.5 (freshness check — consumer of the detect/strip helpers)
 * @see docs/specs/architecture.md §5.2 (build phase — consumer of the apply helpers)
 */

import type { ClaudeHooksFile } from '../targets/claude/schemas.js';

/**
 * Canonical generator identity string embedded in every sentinel. Centralized here so the
 * inline comment block, the JSON `_generated.by` field, and any detector all agree on one
 * literal — there is no second copy to drift.
 */
export const GENERATOR_ID = '@ai-plugin-marketplace/cli';

/**
 * Which sentinel carrier a given generated file uses. Selected by the build step per the
 * artifact's format and host tolerance (§4.3):
 * - `'inline'` — plain-text outputs (comment block prepended).
 * - `'json-field'` — JSON outputs that tolerate an extra top-level `_generated` key.
 * - `'sidecar'` — strict-schema JSON whose host rejects unknown fields; sentinel lives in
 *   a companion `<artifact>.generated` file and the artifact itself is left untouched.
 */
export type SentinelMode = 'inline' | 'json-field' | 'sidecar';

/**
 * Shape of the top-level `_generated` field used by the JSON carrier (§4.3). Serialized with
 * the `_generated` key FIRST so the sentinel is visible at the head of the file.
 */
interface JsonSentinelField {
  /** The {@link GENERATOR_ID} that produced the file. */
  by: string;
  /** Author-authored source path this file was generated from, relative to the plugin dir. */
  source: string;
  /**
   * The `@ai-plugin-marketplace/core` (generation-engine) package version that produced this file,
   * as a bare semver string (e.g. `"0.8.0"`). Read by the build downgrade guard (§4.3.1): a build
   * whose installed core version is OLDER than a stamped version refuses to overwrite the artifact.
   * Serialized LAST within `_generated` so the human-relevant `by`/`source` stay at the head.
   */
  version: string;
}

// ---------------------------------------------------------------------------
// Inline-text carrier
// ---------------------------------------------------------------------------

/** First line of the inline/sidecar comment body. */
const INLINE_LINE_1 = `# Generated by ${GENERATOR_ID}. Do not edit directly.`;
/** Second line of the inline/sidecar comment body. */
const INLINE_LINE_2 = '# Edit the source file listed in the sentinel and run `aipm build`.';
/** Prefix of the third (source) line; the relative source path is appended verbatim. */
const INLINE_SOURCE_PREFIX = '# source: ';
/**
 * Prefix of the fourth (version) line — the generation-engine (`@ai-plugin-marketplace/core`)
 * semver that produced the file, appended verbatim (§4.3.1). Read by the build downgrade guard.
 */
const INLINE_VERSION_PREFIX = '# version: ';

/**
 * Build the canonical inline-text sentinel body for a source path and generator version. This
 * four-line block is shared by the inline carrier (prepended to content) and the sidecar carrier
 * (used as the whole sidecar file). Always terminated by a trailing newline so the following
 * content — or the file end, for a sidecar — starts on a fresh line.
 *
 * The `# version:` line (§4.3.1) is appended AFTER `# source:` so existing three-line sentinels
 * (written before versions were stamped) still parse for `by`/`source`; a missing version line is
 * treated as "unstamped" by {@link readSentinelVersion}.
 *
 * @param source - Author-authored source path, relative to the plugin directory.
 * @param version - The `@ai-plugin-marketplace/core` version that produced the file.
 * @returns The four-line comment block, newline-terminated.
 */
function inlineSentinelBlock(source: string, version: string): string {
  return (
    `${INLINE_LINE_1}\n${INLINE_LINE_2}\n` +
    `${INLINE_SOURCE_PREFIX}${source}\n${INLINE_VERSION_PREFIX}${version}\n`
  );
}

/**
 * Prepend the inline-text sentinel (§4.3) to a plain-text generated file's content.
 *
 * @param content - The generated file body, sans sentinel.
 * @param source - Author-authored source path, relative to the plugin directory.
 * @param version - The `@ai-plugin-marketplace/core` version that produced the file.
 * @returns Content with the four-line sentinel block prepended.
 */
export function applyInlineSentinel(content: string, source: string, version: string): string {
  return inlineSentinelBlock(source, version) + content;
}

// ---------------------------------------------------------------------------
// Sidecar carrier
// ---------------------------------------------------------------------------

/** Suffix appended to an artifact path to form its sidecar sentinel path. */
const SIDECAR_SUFFIX = '.generated';

/**
 * The body of a `<artifact>.generated` sidecar file (§4.3). Identical to the inline-text
 * sentinel block — the sidecar carries no artifact content, only the sentinel.
 *
 * @param source - Author-authored source path, relative to the plugin directory.
 * @param version - The `@ai-plugin-marketplace/core` version that produced the artifact.
 * @returns The four-line sentinel block, newline-terminated.
 */
export function sidecarContent(source: string, version: string): string {
  return inlineSentinelBlock(source, version);
}

/**
 * Derive the sidecar sentinel path for an artifact: `<artifactPath>.generated` (§4.3). The
 * sidecar sits next to the artifact; the artifact itself is left untouched.
 *
 * @param artifactPath - Path to the strict-schema artifact (e.g. `gemini-extension.json`).
 * @returns The sidecar path.
 */
export function sidecarPath(artifactPath: string): string {
  return `${artifactPath}${SIDECAR_SUFFIX}`;
}

// ---------------------------------------------------------------------------
// JSON `_generated`-field carrier
// ---------------------------------------------------------------------------

/**
 * Serialize an object as canonical JSON with a top-level `_generated` sentinel (§4.3). The
 * `_generated` key is emitted FIRST, every other own-enumerable key follows in its original
 * order, and the output uses 2-space indentation with a trailing newline — matching the JSON
 * conventions in `claude/transform.ts`'s `serializeClaudeHooksJson`.
 *
 * Any pre-existing `_generated` key on the input is overwritten by the fresh sentinel rather
 * than duplicated, so re-applying is idempotent at the field level.
 *
 * @param obj - The value to serialize. Treated as a string-keyed object; non-object inputs
 *   (arrays, primitives) cannot carry a top-level field and are rejected.
 * @param source - Author-authored source path, relative to the plugin directory.
 * @param version - The `@ai-plugin-marketplace/core` version that produced the file (§4.3.1).
 * @returns Canonical JSON string with `_generated` first and a trailing `\n`.
 * @throws {TypeError} If `obj` is not a plain JSON object (null, array, or primitive).
 */
export function applyJsonSentinel(obj: unknown, source: string, version: string): string {
  if (typeof obj !== 'object' || obj === null || Array.isArray(obj)) {
    throw new TypeError(
      'applyJsonSentinel: expected a plain object to carry a top-level _generated field',
    );
  }

  const sentinel: JsonSentinelField = { by: GENERATOR_ID, source, version };

  // `_generated` first, then every other own key in its original insertion order. Spreading a
  // pre-existing `_generated` would re-introduce it after ours, so drop it from the rest.
  const rest: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key === '_generated') continue;
    rest[key] = value;
  }

  const withSentinel = { _generated: sentinel, ...rest };
  return JSON.stringify(withSentinel, null, 2) + '\n';
}

/**
 * Convenience overload for validated Claude hooks data, matching the call shape of
 * `serializeClaudeHooksJson`. Equivalent to {@link applyJsonSentinel} with the hooks object.
 *
 * @param data - Validated {@link ClaudeHooksFile}.
 * @param source - Author-authored source path, relative to the plugin directory.
 * @param version - The `@ai-plugin-marketplace/core` version that produced the file (§4.3.1).
 * @returns Canonical JSON string with `_generated` first and a trailing `\n`.
 */
export function applyJsonSentinelToHooks(
  data: ClaudeHooksFile,
  source: string,
  version: string,
): string {
  return applyJsonSentinel(data, source, version);
}

// ---------------------------------------------------------------------------
// Detection / source extraction / stripping (consumed by freshness — §10.5)
// ---------------------------------------------------------------------------

/**
 * Parse JSON content into a string-keyed object, returning `undefined` for malformed JSON or
 * any non-object top-level value (array, primitive, null). Used by the JSON-carrier detectors
 * so a hand-corrupted generated file degrades gracefully rather than throwing.
 */
function parseJsonObject(content: string): Record<string, unknown> | undefined {
  let parsed: unknown;
  try {
    parsed = JSON.parse(content);
  } catch {
    return undefined;
  }
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    return undefined;
  }
  return parsed as Record<string, unknown>;
}

/**
 * Read the `source` from a JSON `_generated` field, validating that the field is a well-formed
 * {@link JsonSentinelField}. Returns `undefined` if absent or malformed.
 */
function readJsonSentinelSource(content: string): string | undefined {
  const obj = parseJsonObject(content);
  if (!obj) return undefined;
  const generated = obj['_generated'];
  if (typeof generated !== 'object' || generated === null || Array.isArray(generated)) {
    return undefined;
  }
  const source = (generated as Record<string, unknown>)['source'];
  return typeof source === 'string' ? source : undefined;
}

/**
 * Read the `source` from an inline/sidecar comment block. Returns `undefined` if the content
 * does not begin with the canonical two-line preamble followed by a `# source:` line.
 */
function readInlineSentinelSource(content: string): string | undefined {
  const lines = content.split('\n');
  if (lines[0] !== INLINE_LINE_1 || lines[1] !== INLINE_LINE_2) return undefined;
  const sourceLine = lines[2];
  if (!sourceLine?.startsWith(INLINE_SOURCE_PREFIX)) return undefined;
  return sourceLine.slice(INLINE_SOURCE_PREFIX.length);
}

/**
 * Read the generation-engine version from an inline/sidecar comment block's `# version:` line
 * (§4.3.1), or `undefined` if the block carries no well-formed sentinel or predates version
 * stamping (a three-line block with no `# version:` line).
 */
function readInlineSentinelVersion(content: string): string | undefined {
  if (readInlineSentinelSource(content) === undefined) return undefined;
  const versionLine = content.split('\n')[3];
  if (!versionLine?.startsWith(INLINE_VERSION_PREFIX)) return undefined;
  return versionLine.slice(INLINE_VERSION_PREFIX.length);
}

/**
 * Read the generation-engine version from a JSON `_generated.version` field (§4.3.1), or
 * `undefined` if absent (an unstamped file), malformed, or not a string.
 */
function readJsonSentinelVersion(content: string): string | undefined {
  const obj = parseJsonObject(content);
  if (!obj) return undefined;
  const generated = obj['_generated'];
  if (typeof generated !== 'object' || generated === null || Array.isArray(generated)) {
    return undefined;
  }
  const version = (generated as Record<string, unknown>)['version'];
  return typeof version === 'string' ? version : undefined;
}

/**
 * Detect whether `content` carries a sentinel for the given carrier (§4.3). For `'sidecar'`,
 * `content` is the sidecar file body (same shape as inline); the artifact itself is never
 * inspected by this function.
 *
 * @param content - File content to inspect (artifact body, or sidecar body for `'sidecar'`).
 * @param mode - Which carrier to check for.
 * @returns `true` iff a well-formed sentinel of that carrier is present.
 */
export function hasSentinel(content: string, mode: SentinelMode): boolean {
  return readSentinelSource(content, mode) !== undefined;
}

/**
 * Extract the author-authored source path recorded in a sentinel, or `undefined` if no
 * well-formed sentinel of the given carrier is present (§10.5 uses this to identify the source
 * and to distinguish generated files from hand-authored ones).
 *
 * @param content - File content to inspect (artifact body, or sidecar body for `'sidecar'`).
 * @param mode - Which carrier to read.
 * @returns The recorded source path, or `undefined`.
 */
export function readSentinelSource(content: string, mode: SentinelMode): string | undefined {
  switch (mode) {
    case 'inline':
    case 'sidecar':
      return readInlineSentinelSource(content);
    case 'json-field':
      return readJsonSentinelSource(content);
  }
}

/**
 * Extract the generation-engine (`@ai-plugin-marketplace/core`) version recorded in a sentinel
 * (§4.3.1), or `undefined` when the content carries no well-formed sentinel of the given carrier
 * OR carries a sentinel that predates version stamping. The build downgrade guard reads this from
 * each committed artifact to detect a stale (older) installed toolkit before overwriting.
 *
 * @param content - File content to inspect (artifact body, or sidecar body for `'sidecar'`).
 * @param mode - Which carrier to read.
 * @returns The recorded generation-engine version, or `undefined`.
 */
export function readSentinelVersion(content: string, mode: SentinelMode): string | undefined {
  switch (mode) {
    case 'inline':
    case 'sidecar':
      return readInlineSentinelVersion(content);
    case 'json-field':
      return readJsonSentinelVersion(content);
  }
}

/**
 * Normalize `content` so that two generated files differing ONLY in their stamped generator
 * version (§4.3.1) compare equal. Used by the freshness check (§10.5) so a version bump alone does
 * NOT flag every artifact as stale: freshness is about CONTENT correctness (wrong hooks, wrong
 * source, missing files), while version safety is enforced separately by the build downgrade guard.
 *
 * The transform is a MINIMAL string edit that removes only the stamp token, preserving all other
 * bytes — so a formatting-only hand-edit of a generated artifact is still detected as stale.
 *
 * - `'json-field'` — remove only the canonical `_generated.version` line `applyJsonSentinel` emits.
 *   Non-canonical, legacy-versionless, or non-`_generated` JSON is returned byte-for-byte unchanged.
 * - `'inline'` / `'sidecar'` — drop the `# version:` line from the sentinel block, if present.
 *   Content with no recognized sentinel is returned unchanged.
 *
 * @param content - File content to normalize.
 * @param mode - Which carrier the content uses.
 * @returns The content with any generator-version stamp removed.
 */
export function withoutGeneratorVersion(content: string, mode: SentinelMode): string {
  switch (mode) {
    case 'inline':
    case 'sidecar':
      return stripInlineVersionLine(content);
    case 'json-field':
      return stripJsonVersionField(content);
  }
}

/** Drop the `# version:` line (§4.3.1) from an inline/sidecar sentinel block, if present. */
function stripInlineVersionLine(content: string): string {
  if (readInlineSentinelVersion(content) === undefined) return content;
  const lines = content.split('\n');
  lines.splice(3, 1); // the # version: line sits at index 3
  return lines.join('\n');
}

/**
 * Matches the `_generated.version` stamp EXACTLY as {@link applyJsonSentinel} emits it. `version`
 * is the last key of the `_generated` object (which is itself the first top-level key), and
 * `JSON.stringify(_, null, 2)` puts that object's keys at a 4-space indent, so the stamp always
 * appears as `,\n    "version": "<value>"` immediately before `_generated`'s closing `\n  }`. The
 * leading comma (after the preceding `source` line) is captured so removing the whole match yields
 * exactly the versionless canonical form. Applied non-globally (first match only): because
 * `_generated` is serialized first, the first such occurrence is always its own version key, never
 * a coincidental deeper `"version"` field.
 */
const CANONICAL_JSON_VERSION_STAMP = /,\n {4}"version": "(?:[^"\\]|\\.)*"(?=\n {2}})/;

/**
 * Remove ONLY the canonical `_generated.version` stamp via a minimal string transform, preserving
 * every other byte. Unlike a parse+re-serialize, this leaves any non-canonical formatting intact,
 * so the freshness check still flags formatting-only hand-edits of a generated JSON artifact as
 * stale — it ignores solely the generator-version token (§4.3.1). Content without the canonical
 * stamp (a legacy versionless file, a hand-reformatted file, or non-`_generated` JSON) is returned
 * byte-for-byte unchanged, so no non-generated file is ever rewritten by the normalization.
 */
function stripJsonVersionField(content: string): string {
  return content.replace(CANONICAL_JSON_VERSION_STAMP, '');
}

/**
 * Remove a sentinel from `content`, returning the body sans sentinel. The inverse of the
 * matching `applyXSentinel`, so freshness (§10.5) can compare an on-disk generated file to
 * freshly-built content modulo the sentinel.
 *
 * - `'inline'` — drops the three-line comment block if present; otherwise returns `content`
 *   unchanged.
 * - `'sidecar'` — the sidecar carries only the sentinel, so the stripped body is the empty
 *   string; if `content` is not a recognized sidecar it is returned unchanged.
 * - `'json-field'` — re-serializes the object without `_generated`, preserving the remaining
 *   keys' order, 2-space indent, and trailing newline. Malformed JSON is returned unchanged.
 *
 * @param content - File content to strip.
 * @param mode - Which carrier to strip.
 * @returns The content with its sentinel removed.
 */
export function stripSentinel(content: string, mode: SentinelMode): string {
  switch (mode) {
    case 'inline':
      return stripInlineSentinel(content);
    case 'sidecar':
      // A sidecar is wholly sentinel; stripping yields an empty body. Leave unrecognized
      // content untouched so a non-sidecar file is not silently emptied.
      return hasSentinel(content, 'sidecar') ? '' : content;
    case 'json-field':
      return stripJsonSentinel(content);
  }
}

/**
 * Drop the leading inline sentinel block, if present. The block is the two-line preamble + the
 * `# source:` line, plus (for post-§4.3.1 output) a trailing `# version:` line. The version line
 * is consumed only when actually present, so a legacy three-line block still strips cleanly.
 */
function stripInlineSentinel(content: string): string {
  if (readInlineSentinelSource(content) === undefined) return content;
  // Remove up to and including the third newline (end of the `# source:` line). Locate it without
  // assuming the source path is newline-free beyond line 3.
  const firstNl = content.indexOf('\n');
  const secondNl = content.indexOf('\n', firstNl + 1);
  const thirdNl = content.indexOf('\n', secondNl + 1);
  const afterSource = content.slice(thirdNl + 1);
  // A `# version:` line (§4.3.1) may follow the source line — consume it too when present.
  if (afterSource.startsWith(INLINE_VERSION_PREFIX)) {
    const fourthNl = content.indexOf('\n', thirdNl + 1);
    return content.slice(fourthNl + 1);
  }
  return afterSource;
}

/** Re-serialize JSON content without its `_generated` field; passthrough on malformed JSON. */
function stripJsonSentinel(content: string): string {
  const obj = parseJsonObject(content);
  if (!obj) return content;
  const rest: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(obj)) {
    if (key === '_generated') continue;
    rest[key] = value;
  }
  return JSON.stringify(rest, null, 2) + '\n';
}
