/**
 * Tests for generated-file sentinels.
 *
 * Covers all three carriers from §4.3 — inline text, JSON `_generated` field, and the
 * `<artifact>.generated` sidecar — across apply, detect, read-source, read-version, strip
 * (round-trip), and the version-agnostic normalization the freshness check uses (§4.3.1, §10.5).
 * All functions under test are pure (no I/O).
 *
 * Expected values are derived by hand from §4.3's literal sentinel block and the JSON output
 * conventions in `claude/transform.ts` (2-space indent, `_generated` first, trailing newline),
 * not captured from program output. The `# version:` line / `_generated.version` field is §4.3.1.
 *
 * @see docs/specs/architecture.md §4.3 (sentinel carriers — governing section)
 * @see docs/specs/architecture.md §4.3.1 (generator-version stamp + downgrade guard)
 * @see docs/specs/architecture.md §10.5 (freshness check — consumer of detect/strip/normalize)
 */

import { describe, expect, it } from 'vitest';

import {
  GENERATOR_ID,
  applyInlineSentinel,
  applyJsonSentinel,
  applyJsonSentinelToHooks,
  hasSentinel,
  readSentinelSource,
  readSentinelVersion,
  sidecarContent,
  sidecarPath,
  stripSentinel,
  withoutGeneratorVersion,
} from './sentinel.js';

// The exact block §4.3/§4.3.1 specify, for source `hooks/claude.yaml` at generator version 0.8.0.
const SOURCE = 'hooks/claude.yaml';
const VERSION = '0.8.0';
const EXPECTED_INLINE_BLOCK =
  '# Generated by @ai-plugin-marketplace/cli. Do not edit directly.\n' +
  '# Edit the source file listed in the sentinel and run `aipm build`.\n' +
  '# source: hooks/claude.yaml\n' +
  '# version: 0.8.0\n';

describe('GENERATOR_ID', () => {
  it('is the canonical CLI package name (§4.3)', () => {
    expect(GENERATOR_ID).toBe('@ai-plugin-marketplace/cli');
  });
});

// ---------------------------------------------------------------------------
// Inline-text carrier
// ---------------------------------------------------------------------------

describe('applyInlineSentinel', () => {
  it('prepends the exact four-line block from §4.3/§4.3.1', () => {
    const result = applyInlineSentinel('body line\n', SOURCE, VERSION);
    expect(result).toBe(EXPECTED_INLINE_BLOCK + 'body line\n');
  });

  it('round-trips: strip(apply(content)) === content', () => {
    const content = 'arbitrary\ngenerated\ncontent\n';
    expect(stripSentinel(applyInlineSentinel(content, SOURCE, VERSION), 'inline')).toBe(content);
  });

  it('round-trips the source: readSentinelSource(apply(content)) === source', () => {
    expect(readSentinelSource(applyInlineSentinel('x', SOURCE, VERSION), 'inline')).toBe(SOURCE);
  });

  it('round-trips the version: readSentinelVersion(apply(content)) === version (§4.3.1)', () => {
    expect(readSentinelVersion(applyInlineSentinel('x', SOURCE, VERSION), 'inline')).toBe(VERSION);
  });

  it('hasSentinel detects an applied inline sentinel', () => {
    expect(hasSentinel(applyInlineSentinel('x', SOURCE, VERSION), 'inline')).toBe(true);
  });

  it('round-trips an empty body', () => {
    const applied = applyInlineSentinel('', SOURCE, VERSION);
    expect(applied).toBe(EXPECTED_INLINE_BLOCK);
    expect(stripSentinel(applied, 'inline')).toBe('');
  });

  it('round-trips an empty source string (edge case)', () => {
    const applied = applyInlineSentinel('body\n', '', VERSION);
    expect(readSentinelSource(applied, 'inline')).toBe('');
    expect(stripSentinel(applied, 'inline')).toBe('body\n');
  });

  it('preserves multi-line body content after stripping', () => {
    const body = 'a\nb\nc\n';
    expect(stripSentinel(applyInlineSentinel(body, SOURCE, VERSION), 'inline')).toBe(body);
  });

  it('still strips a legacy three-line block that predates version stamping', () => {
    // A sentinel written before §4.3.1 has no `# version:` line; stripping must not consume the
    // first body line by mistake.
    const legacy =
      '# Generated by @ai-plugin-marketplace/cli. Do not edit directly.\n' +
      '# Edit the source file listed in the sentinel and run `aipm build`.\n' +
      '# source: hooks/claude.yaml\n';
    expect(readSentinelSource(legacy + 'body\n', 'inline')).toBe(SOURCE);
    expect(readSentinelVersion(legacy + 'body\n', 'inline')).toBeUndefined();
    expect(stripSentinel(legacy + 'body\n', 'inline')).toBe('body\n');
  });
});

describe('inline negative / passthrough cases', () => {
  it('hasSentinel is false for content with no sentinel', () => {
    expect(hasSentinel('just some text\n', 'inline')).toBe(false);
  });

  it('readSentinelSource is undefined for content with no sentinel', () => {
    expect(readSentinelSource('just some text\n', 'inline')).toBeUndefined();
  });

  it('readSentinelVersion is undefined for content with no sentinel', () => {
    expect(readSentinelVersion('just some text\n', 'inline')).toBeUndefined();
  });

  it('stripSentinel returns content unchanged when no sentinel is present', () => {
    const content = '# A user comment that is not the sentinel\nbody\n';
    expect(stripSentinel(content, 'inline')).toBe(content);
  });

  it('is not fooled by only the first line matching', () => {
    const content = '# Generated by @ai-plugin-marketplace/cli. Do not edit directly.\nbody\n';
    expect(hasSentinel(content, 'inline')).toBe(false);
    expect(stripSentinel(content, 'inline')).toBe(content);
  });

  it('requires the third line to be a # source: line', () => {
    const content =
      '# Generated by @ai-plugin-marketplace/cli. Do not edit directly.\n' +
      '# Edit the source file listed in the sentinel and run `aipm build`.\n' +
      'not a source line\n';
    expect(hasSentinel(content, 'inline')).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Sidecar carrier
// ---------------------------------------------------------------------------

describe('sidecarPath', () => {
  it('appends .generated to the artifact path (§4.3)', () => {
    expect(sidecarPath('gemini-extension.json')).toBe('gemini-extension.json.generated');
  });

  it('handles nested artifact paths', () => {
    expect(sidecarPath('.kiro/agents/foo.json')).toBe('.kiro/agents/foo.json.generated');
  });
});

describe('sidecarContent', () => {
  it('is exactly the inline sentinel block', () => {
    expect(sidecarContent(SOURCE, VERSION)).toBe(EXPECTED_INLINE_BLOCK);
  });

  it('hasSentinel detects the sidecar body', () => {
    expect(hasSentinel(sidecarContent(SOURCE, VERSION), 'sidecar')).toBe(true);
  });

  it('readSentinelSource round-trips the source', () => {
    expect(readSentinelSource(sidecarContent(SOURCE, VERSION), 'sidecar')).toBe(SOURCE);
  });

  it('readSentinelVersion round-trips the version (§4.3.1)', () => {
    expect(readSentinelVersion(sidecarContent(SOURCE, VERSION), 'sidecar')).toBe(VERSION);
  });

  it('stripSentinel yields an empty body (sidecar is wholly sentinel)', () => {
    expect(stripSentinel(sidecarContent(SOURCE, VERSION), 'sidecar')).toBe('');
  });

  it('round-trips an empty source string', () => {
    expect(readSentinelSource(sidecarContent('', VERSION), 'sidecar')).toBe('');
  });

  it('leaves unrecognized content untouched rather than emptying it', () => {
    const notASidecar = 'some other file\n';
    expect(hasSentinel(notASidecar, 'sidecar')).toBe(false);
    expect(stripSentinel(notASidecar, 'sidecar')).toBe(notASidecar);
  });
});

// ---------------------------------------------------------------------------
// JSON `_generated`-field carrier
// ---------------------------------------------------------------------------

describe('applyJsonSentinel', () => {
  it('emits the _generated key FIRST with by + source + version (§4.3/§4.3.1)', () => {
    const json = applyJsonSentinel({ name: 'x' }, SOURCE, VERSION);
    const firstKey = Object.keys(JSON.parse(json) as Record<string, unknown>)[0];
    expect(firstKey).toBe('_generated');
    expect((JSON.parse(json) as { _generated: unknown })._generated).toEqual({
      by: GENERATOR_ID, // §4.3: generator id
      source: SOURCE, // §4.3: relative source path
      version: VERSION, // §4.3.1: generation-engine version
    });
  });

  it('uses 2-space indent and a trailing newline (matches serializeClaudeHooksJson)', () => {
    const json = applyJsonSentinel({ name: 'x' }, SOURCE, VERSION);
    expect(json.endsWith('\n')).toBe(true);
    // 2-space indent: a top-level key is indented by exactly two spaces.
    expect(json).toContain('\n  "name": "x"');
  });

  it('preserves pre-existing keys AND their order after _generated', () => {
    const json = applyJsonSentinel({ alpha: 1, beta: 2, gamma: 3 }, SOURCE, VERSION);
    expect(Object.keys(JSON.parse(json) as Record<string, unknown>)).toStrictEqual([
      '_generated',
      'alpha',
      'beta',
      'gamma',
    ]);
  });

  it('overwrites a pre-existing _generated rather than duplicating it', () => {
    const json = applyJsonSentinel(
      { _generated: { by: 'stale', source: 'old', version: '0.0.1' }, x: 1 },
      SOURCE,
      VERSION,
    );
    const parsed = JSON.parse(json) as { _generated: { source: string; version: string } };
    expect(parsed._generated.source).toBe(SOURCE);
    expect(parsed._generated.version).toBe(VERSION);
    // Exactly one _generated key, and it is first.
    expect(Object.keys(parsed)).toStrictEqual(['_generated', 'x']);
  });

  it('round-trips: strip(apply(obj)) re-serializes the object without the sentinel', () => {
    const obj = { name: 'x', nested: { a: 1 } };
    const expected = JSON.stringify(obj, null, 2) + '\n';
    expect(stripSentinel(applyJsonSentinel(obj, SOURCE, VERSION), 'json-field')).toBe(expected);
  });

  it('round-trips the source via readSentinelSource', () => {
    expect(readSentinelSource(applyJsonSentinel({ a: 1 }, SOURCE, VERSION), 'json-field')).toBe(
      SOURCE,
    );
  });

  it('round-trips the version via readSentinelVersion (§4.3.1)', () => {
    expect(readSentinelVersion(applyJsonSentinel({ a: 1 }, SOURCE, VERSION), 'json-field')).toBe(
      VERSION,
    );
  });

  it('hasSentinel detects an applied JSON sentinel', () => {
    expect(hasSentinel(applyJsonSentinel({ a: 1 }, SOURCE, VERSION), 'json-field')).toBe(true);
  });

  it('handles an empty object (edge case): only _generated remains', () => {
    const json = applyJsonSentinel({}, SOURCE, VERSION);
    expect(Object.keys(JSON.parse(json) as Record<string, unknown>)).toStrictEqual(['_generated']);
    expect(stripSentinel(json, 'json-field')).toBe('{}\n');
  });

  it('handles an empty source string (edge case)', () => {
    expect(readSentinelSource(applyJsonSentinel({ a: 1 }, '', VERSION), 'json-field')).toBe('');
  });

  it('throws TypeError for an array input (cannot carry a top-level field)', () => {
    expect(() => applyJsonSentinel([1, 2, 3], SOURCE, VERSION)).toThrow(TypeError);
  });

  it('throws TypeError for null input', () => {
    expect(() => applyJsonSentinel(null, SOURCE, VERSION)).toThrow(TypeError);
  });

  it('throws TypeError for a primitive input', () => {
    expect(() => applyJsonSentinel('a string', SOURCE, VERSION)).toThrow(TypeError);
  });
});

describe('applyJsonSentinelToHooks', () => {
  it('produces the same output as applyJsonSentinel for the same object', () => {
    const hooks = { schemaVersion: '0.1.0', hooks: {} };
    expect(applyJsonSentinelToHooks(hooks, SOURCE, VERSION)).toBe(
      applyJsonSentinel(hooks, SOURCE, VERSION),
    );
  });
});

describe('JSON negative / malformed cases', () => {
  it('hasSentinel is false for valid JSON without _generated', () => {
    expect(hasSentinel('{"name":"x"}', 'json-field')).toBe(false);
  });

  it('readSentinelSource is undefined for valid JSON without _generated', () => {
    expect(readSentinelSource('{"name":"x"}', 'json-field')).toBeUndefined();
  });

  it('readSentinelVersion is undefined for valid JSON without _generated', () => {
    expect(readSentinelVersion('{"name":"x"}', 'json-field')).toBeUndefined();
  });

  it('handles malformed JSON gracefully (no throw)', () => {
    expect(hasSentinel('{not valid json', 'json-field')).toBe(false);
    expect(readSentinelSource('{not valid json', 'json-field')).toBeUndefined();
    expect(readSentinelVersion('{not valid json', 'json-field')).toBeUndefined();
    expect(stripSentinel('{not valid json', 'json-field')).toBe('{not valid json');
  });

  it('treats a non-object JSON top-level (array) as having no sentinel', () => {
    expect(hasSentinel('[1,2,3]', 'json-field')).toBe(false);
    expect(stripSentinel('[1,2,3]', 'json-field')).toBe('[1,2,3]');
  });

  it('ignores a _generated field of the wrong shape (missing source)', () => {
    expect(readSentinelSource('{"_generated":{"by":"x"}}', 'json-field')).toBeUndefined();
  });

  it('reads source but not version from a legacy _generated field without version', () => {
    const legacy = '{"_generated":{"by":"x","source":"hooks/claude.yaml"}}';
    expect(readSentinelSource(legacy, 'json-field')).toBe(SOURCE);
    expect(readSentinelVersion(legacy, 'json-field')).toBeUndefined();
  });

  it('ignores a non-string version field', () => {
    expect(
      readSentinelVersion('{"_generated":{"by":"x","source":"s","version":7}}', 'json-field'),
    ).toBeUndefined();
  });

  it('ignores a non-object _generated field', () => {
    expect(readSentinelSource('{"_generated":"nope"}', 'json-field')).toBeUndefined();
  });
});

// ---------------------------------------------------------------------------
// Version-agnostic normalization (§4.3.1 / §10.5 freshness)
// ---------------------------------------------------------------------------

describe('withoutGeneratorVersion', () => {
  it('makes two json-field artifacts differing only in version compare equal', () => {
    const a = applyJsonSentinel({ name: 'x' }, SOURCE, '0.8.0');
    const b = applyJsonSentinel({ name: 'x' }, SOURCE, '0.9.0');
    expect(a).not.toBe(b); // the raw bytes differ (version stamp)
    expect(withoutGeneratorVersion(a, 'json-field')).toBe(withoutGeneratorVersion(b, 'json-field'));
  });

  it('still distinguishes json-field artifacts that differ in real content', () => {
    const a = applyJsonSentinel({ name: 'x' }, SOURCE, VERSION);
    const b = applyJsonSentinel({ name: 'y' }, SOURCE, VERSION);
    expect(withoutGeneratorVersion(a, 'json-field')).not.toBe(
      withoutGeneratorVersion(b, 'json-field'),
    );
  });

  it('still distinguishes json-field artifacts that differ in the recorded source', () => {
    const a = applyJsonSentinel({ name: 'x' }, 'hooks/claude.yaml', VERSION);
    const b = applyJsonSentinel({ name: 'x' }, 'hooks/claude.yml', VERSION);
    expect(withoutGeneratorVersion(a, 'json-field')).not.toBe(
      withoutGeneratorVersion(b, 'json-field'),
    );
  });

  it('normalizes a legacy versionless json-field artifact to the same form as a versioned one', () => {
    // A file committed before §4.3.1 (no version key) must be considered fresh against a rebuild
    // that now stamps a version, provided the content matches.
    const legacy =
      '{\n  "_generated": {\n    "by": "@ai-plugin-marketplace/cli",\n    "source": "hooks/claude.yaml"\n  },\n  "name": "x"\n}\n';
    const current = applyJsonSentinel({ name: 'x' }, SOURCE, VERSION);
    expect(withoutGeneratorVersion(legacy, 'json-field')).toBe(
      withoutGeneratorVersion(current, 'json-field'),
    );
  });

  it('passes through json content with no _generated field unchanged', () => {
    const content = '{"name":"x"}';
    expect(withoutGeneratorVersion(content, 'json-field')).toBe(content);
  });

  it('does NOT mask a formatting-only edit — reindented JSON stays distinguishable', () => {
    // Copilot #81: the normalization must strip ONLY the version stamp, not canonicalize
    // formatting, so a whitespace-only hand-edit of a generated JSON artifact is still flagged as
    // stale by freshness. Reindent the canonical output (2-space → 4-space) with the SAME data and
    // SAME version; the two must remain unequal after normalization.
    const canonical = applyJsonSentinel({ name: 'x' }, SOURCE, VERSION);
    const reindented = JSON.stringify(JSON.parse(canonical), null, 4) + '\n';
    expect(reindented).not.toBe(canonical); // formatting differs
    expect(withoutGeneratorVersion(reindented, 'json-field')).not.toBe(
      withoutGeneratorVersion(canonical, 'json-field'),
    );
  });

  it('strips the version but preserves the exact bytes of everything else', () => {
    // The versionless normalization of a canonical artifact is byte-identical to the same artifact
    // built without a version stamp (a minimal transform, not a re-serialization).
    const withVersion = applyJsonSentinel({ hooks: { a: 1 } }, SOURCE, VERSION);
    const expectedVersionless =
      '{\n' +
      '  "_generated": {\n' +
      '    "by": "@ai-plugin-marketplace/cli",\n' +
      '    "source": "hooks/claude.yaml"\n' +
      '  },\n' +
      '  "hooks": {\n' +
      '    "a": 1\n' +
      '  }\n' +
      '}\n';
    expect(withoutGeneratorVersion(withVersion, 'json-field')).toBe(expectedVersionless);
  });

  it('passes through malformed json unchanged', () => {
    expect(withoutGeneratorVersion('{not json', 'json-field')).toBe('{not json');
  });

  it('makes two sidecar bodies differing only in version compare equal', () => {
    const a = sidecarContent(SOURCE, '0.8.0');
    const b = sidecarContent(SOURCE, '0.9.0');
    expect(a).not.toBe(b);
    expect(withoutGeneratorVersion(a, 'sidecar')).toBe(withoutGeneratorVersion(b, 'sidecar'));
  });

  it('drops the # version: line from an inline block, leaving the three-line body', () => {
    const stripped = withoutGeneratorVersion(sidecarContent(SOURCE, VERSION), 'inline');
    expect(stripped).toBe(
      '# Generated by @ai-plugin-marketplace/cli. Do not edit directly.\n' +
        '# Edit the source file listed in the sentinel and run `aipm build`.\n' +
        '# source: hooks/claude.yaml\n',
    );
  });

  it('passes through a legacy versionless inline block unchanged', () => {
    const legacy =
      '# Generated by @ai-plugin-marketplace/cli. Do not edit directly.\n' +
      '# Edit the source file listed in the sentinel and run `aipm build`.\n' +
      '# source: hooks/claude.yaml\n';
    expect(withoutGeneratorVersion(legacy, 'sidecar')).toBe(legacy);
  });

  it('passes through non-sentinel content (e.g. a static script body) unchanged', () => {
    const script = '#!/usr/bin/env node\nconsole.log("hi");\n';
    expect(withoutGeneratorVersion(script, 'sidecar')).toBe(script);
  });
});
