/**
 * Tests for generated-file sentinels.
 *
 * Covers all three carriers from §4.3 — inline text, JSON `_generated` field, and the
 * `<artifact>.generated` sidecar — across apply, detect, read-source, and strip (round-trip).
 * All functions under test are pure (no I/O).
 *
 * Expected values are derived by hand from §4.3's literal sentinel block and the JSON output
 * conventions in `claude/transform.ts` (2-space indent, `_generated` first, trailing newline),
 * not captured from program output.
 *
 * @see docs/specs/architecture.md §4.3 (sentinel carriers — governing section)
 * @see docs/specs/architecture.md §10.5 (freshness check — consumer of detect/strip)
 */

import { describe, expect, it } from 'vitest';

import {
  GENERATOR_ID,
  applyInlineSentinel,
  applyJsonSentinel,
  applyJsonSentinelToHooks,
  hasSentinel,
  readSentinelSource,
  sidecarContent,
  sidecarPath,
  stripSentinel,
} from './sentinel.js';

// The exact three-line block §4.3 specifies, for source `hooks/claude.yaml`.
const SOURCE = 'hooks/claude.yaml';
const EXPECTED_INLINE_BLOCK =
  '# Generated by @ai-plugin-marketplace/cli. Do not edit directly.\n' +
  '# Edit the source file listed in the sentinel and run `aipm build`.\n' +
  '# source: hooks/claude.yaml\n';

describe('GENERATOR_ID', () => {
  it('is the canonical CLI package name (§4.3)', () => {
    expect(GENERATOR_ID).toBe('@ai-plugin-marketplace/cli');
  });
});

// ---------------------------------------------------------------------------
// Inline-text carrier
// ---------------------------------------------------------------------------

describe('applyInlineSentinel', () => {
  it('prepends the exact three-line block from §4.3', () => {
    const result = applyInlineSentinel('body line\n', SOURCE);
    expect(result).toBe(EXPECTED_INLINE_BLOCK + 'body line\n');
  });

  it('round-trips: strip(apply(content)) === content', () => {
    const content = 'arbitrary\ngenerated\ncontent\n';
    expect(stripSentinel(applyInlineSentinel(content, SOURCE), 'inline')).toBe(content);
  });

  it('round-trips the source: readSentinelSource(apply(content)) === source', () => {
    expect(readSentinelSource(applyInlineSentinel('x', SOURCE), 'inline')).toBe(SOURCE);
  });

  it('hasSentinel detects an applied inline sentinel', () => {
    expect(hasSentinel(applyInlineSentinel('x', SOURCE), 'inline')).toBe(true);
  });

  it('round-trips an empty body', () => {
    const applied = applyInlineSentinel('', SOURCE);
    expect(applied).toBe(EXPECTED_INLINE_BLOCK);
    expect(stripSentinel(applied, 'inline')).toBe('');
  });

  it('round-trips an empty source string (edge case)', () => {
    const applied = applyInlineSentinel('body\n', '');
    expect(readSentinelSource(applied, 'inline')).toBe('');
    expect(stripSentinel(applied, 'inline')).toBe('body\n');
  });

  it('preserves multi-line body content after stripping', () => {
    const body = 'a\nb\nc\n';
    expect(stripSentinel(applyInlineSentinel(body, SOURCE), 'inline')).toBe(body);
  });
});

describe('inline negative / passthrough cases', () => {
  it('hasSentinel is false for content with no sentinel', () => {
    expect(hasSentinel('just some text\n', 'inline')).toBe(false);
  });

  it('readSentinelSource is undefined for content with no sentinel', () => {
    expect(readSentinelSource('just some text\n', 'inline')).toBeUndefined();
  });

  it('stripSentinel returns content unchanged when no sentinel is present', () => {
    const content = '# A user comment that is not the sentinel\nbody\n';
    expect(stripSentinel(content, 'inline')).toBe(content);
  });

  it('is not fooled by only the first line matching', () => {
    const content = '# Generated by @ai-plugin-marketplace/cli. Do not edit directly.\nbody\n';
    expect(hasSentinel(content, 'inline')).toBe(false);
    expect(stripSentinel(content, 'inline')).toBe(content);
  });

  it('requires the third line to be a # source: line', () => {
    const content =
      '# Generated by @ai-plugin-marketplace/cli. Do not edit directly.\n' +
      '# Edit the source file listed in the sentinel and run `aipm build`.\n' +
      'not a source line\n';
    expect(hasSentinel(content, 'inline')).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Sidecar carrier
// ---------------------------------------------------------------------------

describe('sidecarPath', () => {
  it('appends .generated to the artifact path (§4.3)', () => {
    expect(sidecarPath('gemini-extension.json')).toBe('gemini-extension.json.generated');
  });

  it('handles nested artifact paths', () => {
    expect(sidecarPath('.kiro/agents/foo.json')).toBe('.kiro/agents/foo.json.generated');
  });
});

describe('sidecarContent', () => {
  it('is exactly the inline sentinel block', () => {
    expect(sidecarContent(SOURCE)).toBe(EXPECTED_INLINE_BLOCK);
  });

  it('hasSentinel detects the sidecar body', () => {
    expect(hasSentinel(sidecarContent(SOURCE), 'sidecar')).toBe(true);
  });

  it('readSentinelSource round-trips the source', () => {
    expect(readSentinelSource(sidecarContent(SOURCE), 'sidecar')).toBe(SOURCE);
  });

  it('stripSentinel yields an empty body (sidecar is wholly sentinel)', () => {
    expect(stripSentinel(sidecarContent(SOURCE), 'sidecar')).toBe('');
  });

  it('round-trips an empty source string', () => {
    expect(readSentinelSource(sidecarContent(''), 'sidecar')).toBe('');
  });

  it('leaves unrecognized content untouched rather than emptying it', () => {
    const notASidecar = 'some other file\n';
    expect(hasSentinel(notASidecar, 'sidecar')).toBe(false);
    expect(stripSentinel(notASidecar, 'sidecar')).toBe(notASidecar);
  });
});

// ---------------------------------------------------------------------------
// JSON `_generated`-field carrier
// ---------------------------------------------------------------------------

describe('applyJsonSentinel', () => {
  it('emits the _generated key FIRST with by + source (§4.3)', () => {
    const json = applyJsonSentinel({ name: 'x' }, SOURCE);
    const firstKey = Object.keys(JSON.parse(json) as Record<string, unknown>)[0];
    expect(firstKey).toBe('_generated');
    expect((JSON.parse(json) as { _generated: unknown })._generated).toEqual({
      by: GENERATOR_ID, // §4.3: generator id
      source: SOURCE, // §4.3: relative source path
    });
  });

  it('uses 2-space indent and a trailing newline (matches serializeClaudeHooksJson)', () => {
    const json = applyJsonSentinel({ name: 'x' }, SOURCE);
    expect(json.endsWith('\n')).toBe(true);
    // 2-space indent: a top-level key is indented by exactly two spaces.
    expect(json).toContain('\n  "name": "x"');
  });

  it('preserves pre-existing keys AND their order after _generated', () => {
    const json = applyJsonSentinel({ alpha: 1, beta: 2, gamma: 3 }, SOURCE);
    expect(Object.keys(JSON.parse(json) as Record<string, unknown>)).toStrictEqual([
      '_generated',
      'alpha',
      'beta',
      'gamma',
    ]);
  });

  it('overwrites a pre-existing _generated rather than duplicating it', () => {
    const json = applyJsonSentinel({ _generated: { by: 'stale', source: 'old' }, x: 1 }, SOURCE);
    const parsed = JSON.parse(json) as { _generated: { source: string } };
    expect(parsed._generated.source).toBe(SOURCE);
    // Exactly one _generated key, and it is first.
    expect(Object.keys(parsed)).toStrictEqual(['_generated', 'x']);
  });

  it('round-trips: strip(apply(obj)) re-serializes the object without the sentinel', () => {
    const obj = { name: 'x', nested: { a: 1 } };
    const expected = JSON.stringify(obj, null, 2) + '\n';
    expect(stripSentinel(applyJsonSentinel(obj, SOURCE), 'json-field')).toBe(expected);
  });

  it('round-trips the source via readSentinelSource', () => {
    expect(readSentinelSource(applyJsonSentinel({ a: 1 }, SOURCE), 'json-field')).toBe(SOURCE);
  });

  it('hasSentinel detects an applied JSON sentinel', () => {
    expect(hasSentinel(applyJsonSentinel({ a: 1 }, SOURCE), 'json-field')).toBe(true);
  });

  it('handles an empty object (edge case): only _generated remains', () => {
    const json = applyJsonSentinel({}, SOURCE);
    expect(Object.keys(JSON.parse(json) as Record<string, unknown>)).toStrictEqual(['_generated']);
    expect(stripSentinel(json, 'json-field')).toBe('{}\n');
  });

  it('handles an empty source string (edge case)', () => {
    expect(readSentinelSource(applyJsonSentinel({ a: 1 }, ''), 'json-field')).toBe('');
  });

  it('throws TypeError for an array input (cannot carry a top-level field)', () => {
    expect(() => applyJsonSentinel([1, 2, 3], SOURCE)).toThrow(TypeError);
  });

  it('throws TypeError for null input', () => {
    expect(() => applyJsonSentinel(null, SOURCE)).toThrow(TypeError);
  });

  it('throws TypeError for a primitive input', () => {
    expect(() => applyJsonSentinel('a string', SOURCE)).toThrow(TypeError);
  });
});

describe('applyJsonSentinelToHooks', () => {
  it('produces the same output as applyJsonSentinel for the same object', () => {
    const hooks = { schemaVersion: '0.1.0', hooks: {} };
    expect(applyJsonSentinelToHooks(hooks, SOURCE)).toBe(applyJsonSentinel(hooks, SOURCE));
  });
});

describe('JSON negative / malformed cases', () => {
  it('hasSentinel is false for valid JSON without _generated', () => {
    expect(hasSentinel('{"name":"x"}', 'json-field')).toBe(false);
  });

  it('readSentinelSource is undefined for valid JSON without _generated', () => {
    expect(readSentinelSource('{"name":"x"}', 'json-field')).toBeUndefined();
  });

  it('handles malformed JSON gracefully (no throw)', () => {
    expect(hasSentinel('{not valid json', 'json-field')).toBe(false);
    expect(readSentinelSource('{not valid json', 'json-field')).toBeUndefined();
    expect(stripSentinel('{not valid json', 'json-field')).toBe('{not valid json');
  });

  it('treats a non-object JSON top-level (array) as having no sentinel', () => {
    expect(hasSentinel('[1,2,3]', 'json-field')).toBe(false);
    expect(stripSentinel('[1,2,3]', 'json-field')).toBe('[1,2,3]');
  });

  it('ignores a _generated field of the wrong shape (missing source)', () => {
    expect(readSentinelSource('{"_generated":{"by":"x"}}', 'json-field')).toBeUndefined();
  });

  it('ignores a non-object _generated field', () => {
    expect(readSentinelSource('{"_generated":"nope"}', 'json-field')).toBeUndefined();
  });
});
